version: '3.8'
services:

  php_apache:
    container_name: php_apache
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
     MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/project.sql:/docker-entrypoint-initdb.d/project.sql
      - ./db/project1.sql:/docker-entrypoint-initdb.d/project1.sql
      - ./db/nciipc.sql:/docker-entrypoint-initdb.d/nciipc.sql
      - ./db/redteam.sql:/docker-entrypoint-initdb.d/redteam.sql
      - ./db/redteam-2023.sql:/docker-entrypoint-initdb.d/redteam-2023.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8081:8081'
