version: '3.8'

services:
  php_apache:
    container_name: php_apache
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    volumes: 
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      custom_network:
        ipv4_address: 10.0.0.45

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/project.sql:/docker-entrypoint-initdb.d/project.sql
      - ./db/project1.sql:/docker-entrypoint-initdb.d/project1.sql
      - ./db/nciipc.sql:/docker-entrypoint-initdb.d/nciipc.sql
      - ./db/redteam.sql:/docker-entrypoint-initdb.d/redteam.sql
      - ./db/redteam_2023.sql:/docker-entrypoint-initdb.d/redteam_2023.sql
    networks:
      custom_network:
        ipv4_address: 10.0.0.61

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8081:8081'
    networks:
      custom_network:
        ipv4_address: 10.0.0.64

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
